var GAME_LEVELS = [
  ["                                zz                   z                          ",
   "                                                    zzz                         ",
   "                                                     z                          ",
   "             zzz                                                                ",
   "            zzzzz                                                               ",
   "            zzzzz                                                               ",
   "             zzz                                                     xyyyx      ",
   "                                                   yy      yy    xyy!yyx        ",
   "        yyy                         o o      yy    xxx           xy!!!yx        ",
   "        yyy                      xxxxx       xx                  xyy!yyx        ",
   "        yyy                        yyyyy          00               xx           ",
   "        yyy                             o o      yy    xxx        x!!!x         ",
   "        yyy        zz                 xxxx     xx                 x!!!x         ",
   "        yyy       zzzz                                yy         x  !  x        ",
   "                zzzzzzzz            o o    yy    xxx             x !!!x         ",
   "                 zz  zz            xxxx       xx                  x! x          ",
   "                  z  z             yyyyy                           xvx          ",
   "                                                  yyyyyy                  xx    ",
   "  xx                                      o o     xxxx                     x    ",
   "  x                     o                xxxxxx         o o              x      ",
   "  x                                    yyyyyyyy                            x    ",
   "  x          xxxx       o                                           y yyy    x  ",
   "  x  @       x  x                                                   xxx      x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxx   xxxxxxx    xxxxxxxxxx   ",
   "                              x   x                x     x      x!!x            ",
   "                              x!!!x                x!!!!!x      x!!x            ",
   "                              x!!!x                x!!!!!x      x!!x            ",
   "                              x!!!x                x!!!!!x      x!!x            ",
   "                              xxxxx                xxxxxxx      x!!x            ",
   "                              x!!!x                x!!!!!x      x!!x            ",
   "                                                                                ",
   "                                                                                "],
  ["         zzzz                        x!!x                         xxxxxxx                                    x!x  ",
   "       zzzzzzzz                      x!!x                     xxxx     xxxx                                  x!x  ",
   "        zz  zz                        x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "         z  z                         xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                    zz                                       xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                    zz                                        xx!!!!!!!!!!!xx            v                        ",
   "    zzzzzzzz        zz                                           xxxx!!!!!xxxx                                    ",
   "      zzzz                      zzzz               x     x            xxxxxxx        xxx         xxx              ",
   "                             zzzzzzzzzz        x     x                           x x         x x                  ",
   "                               zz  zz          x     x                             x         x                    ",
   "                               zz  zz              x     x                             xx        x                ",
   "             xxxxx                    yyyy     xx    x                             x         x                    ",
   "           yy          yyyyy        xxxx       x     x      o  o     x   x         x         x                    ",
   "         yy  xx    xxxxxxxx     x o x          x    xx               x   x   x               x                    ",
   "     @   xx  x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                 zzzz                      o                                                                  ",
   "                zzzzzz                                                                                        ",
   "                 zzzz                       x                                                                 ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "           zz                            xxx                                                                  ",
   "          zzzz                            x x                 !!!        !!!  xxx                             ",
   "          zzzz                             x x              !x!        !x!                                    ",
   "           zz                         xxx xxx               x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x   oooo   x      x!!!x           zzzz            ",
   "                                      x !! x                 xxxxxxxxxxxx       xxx          zzzzzzz          ",
   "                                     xx   xx      x   x      x                                zz zz           ",
   "               zzzz                       x   xxxxxxxxx   xxxxxxxx              x x                           ",
   "                                      x   x           x   yyyyyyyyyy                 x!!!x                    ",
   "                                      x   x           x                     xxx                               ",
   "                             zz      xx!!!xx          x                       yyyy                            ",
   "                                      x!!!x= = = =    x            zzzz               oooo                    ",
   "                                      x!!!x           x           zzzzzz      zzzzzz                          ",
   "                                      x   x    = = = =x     o      zzzz       xxxxxx                          ",
   "                                                                                                 oo           ",
   "                                     xx   xx          x                       z!!!z                           ",
   "                              o   o   x   x           x     xxxxxx                  zzz        xxx            ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx          x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                yyy          x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                    xxxx     xx           xx                                         xxx                      ",
   "  xxx                  yy     x     x     x                                         x!!!x                xxx  ",
   "  x x      z z          xx       x    xxx    x                                       xxx               x x    ",
   "  x       zzzz               x    xxx    xxxxxxx                        xxxxx                              x  ",
   "  x      zzz zzz     yyy         x           x                              x   x                          x  ",
   "  x       zzzzz     xxxx     xx           x                              x x x                             x  ",
   "  x                    yyyyyyy                   x       |xxxx|    |xxxx| xxx xxx                          x  ",
   "  x    @                    xxxx           x!!x    x!!!!x    x!!!!x    xx   xx                 x         x    ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
	["                                                                                                             ",
	"                                                   @                                                          ",
	"                                                  xxx                                                         ",
	"                                                                                                              ",
	"                    XXX       xxx       xxx       xxx        xxxxxx   xx                                      ",
	"                     xxx     xxxxx     xxx        xxx        xxx xxx  xx                                      ",
	"                      xxx   xxx xxx   xxx         xxx        xxx  xxx xx                                      ",
	"                       xxx xxx   xxx xxx          xxx        xxx   xxxxx                                      ",
	"                        xxxxx     xxxxx           xxx        xxx    xxxx                                      ",
	"                                                                                                              ",
	"                                                                                                              ",
	"                                                                                                              ",
	"                                                                                                              ",
	"                                                                                                              ",
	"                                                                                                              ",
	"                                                                                                              ",
	"  x                                                                                                           ",
	"  x                                                                                                           ",
	" x       x   x       x   x                 yy                  x     x                     				   ",
	"  x        xxxxx       xxxxx       xxxxx     yyyyy                                                            ",
	"  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
	"        x                 x                =x   x                     xxx                                     ",
	"        xxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxx   xxxx                                                        ",
	"                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	"                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
